### Crear solicitud nueva con cliente y ubicaciones nuevas
POST http://localhost:8001/api/solicitudes
Content-Type: application/json

{
  "tiempoEstimado": 48,
  "costoEstimado": 12000.5,
  "tiempoReal": null,
  "costoFinal": null,
  "estado": null,

  "cliente": {
    "id": null,
    "nombre": "Carlos",
    "apellido": "Gomez",
    "telefono": "3515554444",
    "direccion": "Barrio Alberdi 450",
    "dni": 45456789
  },

  "contenedor": {
    "id": null,
    "peso": 1000.0,
    "volumen": 20.0,
    "estado": "borrador",
    "costoVolumen": 150.0
  },

  "origen": {
    "id": null,
    "nombre": "Deposito A",
    "tipo": "Deposito",
    "latitud": -31.4135,
    "longitud": -64.18105
  },

  "destino": {
    "id": null,
    "nombre": "Deposito B",
    "tipo": "Deposito",
    "latitud": -32.9471,
    "longitud": -60.6985
  }
}

### Obtener todas las solicitudes
GET http://localhost:8001/api/solicitudes
Accept: application/json

### Obtener solicitud por id
GET http://localhost:8001/api/solicitudes/1
Accept: application/json

### Actualizar solicitud
PUT http://localhost:8001/api/solicitudes/1
Content-Type: application/json

{
  "tiempoEstimado": 50,
  "costoEstimado": 12500.0,
  "estado": "programada"
}

### Eliminar solicitud
DELETE http://localhost:8001/api/solicitudes/1
