### Crear una solicitud (POST)
POST http://localhost:8001/api/solicitudes
Content-Type: application/json

{
  "estado": null,
  "costoEstimado": 5000,
  "tiempoEstimado": 48,
  "tiempoReal": null,
  "costoFinal": null,
  "cliente": {
    "nombre": "Juan",
    "apellido": "Perez",
    "telefono": "123456789",
    "direccion": "Calle Falsa 123",
    "dni": "12345678"
  },
  "contenedor": {
    "peso": 1000,
    "volumen": 10,
    "estado": "vacío",
    "costoVolumen": 200
  },
  "origen": {
    "nombre": "Deposito A",
    "tipo": "Deposito",
    "latitud": -31.4201,
    "longitud": -64.1888
  },
  "destino": {
    "nombre": "Deposito B",
    "tipo": "Deposito",
    "latitud": -31.4300,
    "longitud": -64.2000
  },
  "seguimiento": []
}

### Actualizar una solicitud (PUT)
PUT http://localhost:8001/api/solicitudes/2
Content-Type: application/json

{
  "estado": "programada",
  "costoEstimado": 5500,
  "tiempoEstimado": 50
}

### Obtener una solicitud por ID (GET)
GET http://localhost:8001/api/solicitudes/1

### Obtener todas las solicitudes (GET)
GET http://localhost:8001/api/solicitudes

### Eliminar una solicitud (DELETE)
DELETE http://localhost:8001/api/solicitudes/1
